---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsqlpv 
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pgsqlvol1/
