---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-cli
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cli
    spec:
      containers:
        - name: mssql-cli
          image: ericskang/tools:mssql-cli
          command: [bash, -c, "tail -f /dev/null"]
      imagePullSecrets: 
        - name: mykey
          