---
kind: Service
apiVersion: v1
metadata:
  name: webapp
  namespace: production
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: ericskang/webapp:latest
          ports:
            - containerPort: 3000
