---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlpvclaim
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "managed-nfs-storage"
  resources:
    requests:
      storage: 10Gi

