---
kind: Service
apiVersion: v1
metadata:
  name: webapp
  namespace: production
spec:
  selector:
    app: webapp
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort 

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
        - name: webapp
          image: ericskang/webapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


