---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlnfs1 
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: "/export/pvc-sql1"
    server: "192.168.1.119"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlnfs2 
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: "/export/pvc-sql2"
    server: "192.168.1.119"
