---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlpvclaim1
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlpvclaim2
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
