---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql
  namespace: sqldevops
  lables:
    app: unittest
    version: latest
spec:
  strategy:
    type: Recreate
  selector: 
    matchLabels: 
      app: unittest
      tier: backend
      version: latest
  template:
    metadata:
      labels:
        app: unittest
        tier: backend
        version: latest
    spec:
      containers:
        - image: sqldevopsacs.azurecr.io/wwi_test:latest
          name: mssql
          imagePullPolicy: Always
      imagePullSecrets:
        - name: mssqlkey

---

kind: Service
apiVersion: v1
metadata:
  name: mssql
  namespace: sqldevops
spec:
  selector:
    app: unittest
    tier: backend
    version: latest
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP

--- 

kind: Service
apiVersion: v1
metadata:
  name: slacker-runner
  namespace: sqldevops
spec:
  selector:
    app: unittest
    tier: frontend
    version: latest
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: slacker-runner
  namespace: sqldevops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unittest
        tier: frontend
        version: latest
    spec:
      containers:
        - name: slacker-runner
          image: sqldevopsacs.azurecr.io/slacker-node-runner:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: mssqlkey
---